language: go

services:
    - docker

notifications:
    webhooks:
        urls:
            - https://ipugh.xmatters.com/api/integration/1/functions/67c8782c-4033-4a11-94f0-cc0c90222bf5/triggers?apiKey=40c05517-3710-482e-9d81-ed8eaea779e5
